import { defineModule } from "@/lib/define-module";
import View from "./View";

export default defineModule({
  slug: "work-sync-digest",
  title: "Weekly Work-Sync Digest",
  owner: "Yizhou",
  issue: 121,
  week: 6,
  order: 40,
  summary:
    "Deterministic W30 digest generated by scripts/work_sync.py — git metadata plus a sanitized activity export, with honest source coverage.",
  View,
});
